# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: rest-with-aspnet-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=api_rest_udemy
      - bind-address=0.0.0.0
    ports:
      - 3308:3306
    networks:
      - udemy-network
  restwithaspnet:
    image: restwithaspnet
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      - "MySqlConnection:MySqlConnectionString=Server=db;database=api_rest_udemy;uid=root;pwd=root"
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=db
    ports:
      - 5000:80
    depends_on: 
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge